// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTranscription() {
  return window['go']['main']['App']['CancelTranscription']();
}

export function CheckRequirements() {
  return window['go']['main']['App']['CheckRequirements']();
}

export function GetGpuVramGB() {
  return window['go']['main']['App']['GetGpuVramGB']();
}

export function GetStartupVideoPath() {
  return window['go']['main']['App']['GetStartupVideoPath']();
}

export function InstallCudaLibraries() {
  return window['go']['main']['App']['InstallCudaLibraries']();
}

export function IsSendToRegistered() {
  return window['go']['main']['App']['IsSendToRegistered']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RegisterSendTo() {
  return window['go']['main']['App']['RegisterSendTo']();
}

export function SelectVideoFileDialog() {
  return window['go']['main']['App']['SelectVideoFileDialog']();
}

export function TranscribeVideo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TranscribeVideo'](arg1, arg2, arg3, arg4);
}

export function UnregisterSendTo() {
  return window['go']['main']['App']['UnregisterSendTo']();
}

export function ValidateVideoFile(arg1) {
  return window['go']['main']['App']['ValidateVideoFile'](arg1);
}
