// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelEnvironmentInstallation() {
  return window['go']['main']['App']['CancelEnvironmentInstallation']();
}

export function CancelTranscription() {
  return window['go']['main']['App']['CancelTranscription']();
}

export function CheckRequirements() {
  return window['go']['main']['App']['CheckRequirements']();
}

export function GetGpuVramGB() {
  return window['go']['main']['App']['GetGpuVramGB']();
}

export function GetStartupVideoPath() {
  return window['go']['main']['App']['GetStartupVideoPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallCudaLibraries() {
  return window['go']['main']['App']['InstallCudaLibraries']();
}

export function InstallPortableEnvironment() {
  return window['go']['main']['App']['InstallPortableEnvironment']();
}

export function IsSendToRegistered() {
  return window['go']['main']['App']['IsSendToRegistered']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RegisterSendTo() {
  return window['go']['main']['App']['RegisterSendTo']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectTextFileDialog() {
  return window['go']['main']['App']['SelectTextFileDialog']();
}

export function SelectVideoFileDialog() {
  return window['go']['main']['App']['SelectVideoFileDialog']();
}

export function TranscribeVideo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TranscribeVideo'](arg1, arg2, arg3, arg4, arg5);
}

export function UnregisterSendTo() {
  return window['go']['main']['App']['UnregisterSendTo']();
}

export function ValidateVideoFile(arg1) {
  return window['go']['main']['App']['ValidateVideoFile'](arg1);
}
