// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelTranscription():Promise<void>;

export function CheckRequirements():Promise<main.RequirementsStatus>;

export function GetGpuVramGB():Promise<number>;

export function GetStartupVideoPath():Promise<string>;

export function InstallCudaLibraries():Promise<void>;

export function IsSendToRegistered():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function RegisterSendTo():Promise<void>;

export function SelectVideoFileDialog():Promise<string>;

export function TranscribeVideo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function UnregisterSendTo():Promise<void>;

export function ValidateVideoFile(arg1:string):Promise<main.VideoValidationResult>;
