// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelEnvironmentInstallation():Promise<void>;

export function CancelTranscription():Promise<void>;

export function CheckRequirements():Promise<main.RequirementsStatus>;

export function GetGpuVramGB():Promise<number>;

export function GetStartupVideoPath():Promise<string>;

export function GetVersion():Promise<string>;

export function InstallCudaLibraries():Promise<void>;

export function InstallPortableEnvironment():Promise<void>;

export function IsSendToRegistered():Promise<boolean>;

export function LoadConfig():Promise<main.AppConfig>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RegisterSendTo():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectTextFileDialog():Promise<string>;

export function SelectVideoFileDialog():Promise<Array<string>>;

export function TranscribeVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UnregisterSendTo():Promise<void>;

export function ValidateVideoFile(arg1:string):Promise<main.VideoValidationResult>;
